# Generated by Django 5.2 on 2025-04-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="publisher_id",
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
